### ISSUE TITLE
foreign key impliment

### ISSUE THREAD

**Issue by theshubhamchugh** [Lecturize/Laravel-Tags#3]
can we add foreign key relations between taggables->tag_id and tags->id ? 

its looks like a relation implemented in migration but foreign is not there

**Comment by AlexanderPoellmann** [comment]
There is a constraint defined in the migration:

```
$table->integer('tag_id')
    ->nullable()
    ->unsigned()
    ->references('id')
    ->on($this->table)
    ->onDelete('cascade');
```
